# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-03 13:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


def add_partner_to_courses(apps, schema_editor):
    Course = apps.get_model("courses", "Course")

    for course in Course.objects.all():
        course.partner = course.site.siteconfiguration.partner
        course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_partner_default_site'),
        ('courses', '0007_auto_20180119_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='partner.Partner'),
        ),
        migrations.RunPython(add_partner_to_courses, migrations.RunPython.noop),
    ]
